view:
  site:
    websiteName: Pi社区
    websiteLogoUrl: https://blog.hhui.top/hexblog/images/avatar.jpg
    websiteFaviconIconUrl: https://blog.hhui.top/hexblog/images/avatar.jpg
    contactMeTitle: 联系我 - xieyun
    contactMeWxQrCode: https://blog.hhui.top/hexblog/images/avatar.jpg
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 备案记录